services:
  db:
    container_name: postgres-backend-api
    image: postgres:latest
    environment:
      POSTGRES_DB: backend_api
      POSTGRES_USER: backend_api
      POSTGRES_PASSWORD: 5001
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: